### ISSUE TITLE
Implement organization by CAC

### ISSUE THREAD

**Issue by jpadilla** [codeforct/wp-amplify-legislator-database#5]
https://codeforct.slack.com/archives/CMMJ1AQH2/p1568942298007900

**Comment by jpadilla** [comment]
@automatedempire and I started hacking on this during today's meetup.

We worked on figuring out how we could replicate the organization of representatives/senators by CAC.

I built https://glitch.com/edit/#!/interesting-moss to extract data from https://www.cga.ct.gov/asp/content/townlist.asp. Example https://interesting-moss.glitch.me/data.json

@automatedempire figured out how to combine this information with the existing legislator database and will share some reproducible later on. At that point I can attempt to reproduce in this project.

Thanks again Adam!

**Comment by danpetrow** [comment]
Pull request #9 from Adam gets the data that we wanted to organize by CAC but it needs to be integrated with the wordpress plugin at this point.

Adam's work basically gets all the data into a new mysql table. The PR description has a query we can do to that table to fetch data. At a minimum, on the plugin side we'll need to query that table when generating the report.
